# Generated by Django 4.2.4 on 2023-10-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='renter_id',
        ),
        migrations.AlterField(
            model_name='flat',
            name='flat_after_discount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='flat',
            name='flat_discount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='flat',
            name='flat_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='flat',
            name='flat_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='flat',
            name='floor_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='flat',
            name='nor_name',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='flat',
            name='room_size',
            field=models.IntegerField(),
        ),
    ]
