# Generated by Django 4.2.4 on 2023-10-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0003_remove_flat_flat_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='flat_after_discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='flat_details',
            field=models.TextField(max_length=1000),
        ),
    ]
