# Generated by Django 4.2.4 on 2023-10-16 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0009_alter_flat_flat_after_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='flat_after_discount',
            new_name='flat_discount',
        ),
    ]
