# Generated by Django 4.2.4 on 2023-09-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number1', models.CharField(max_length=15)),
                ('phone_number2', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('number_of_members', models.PositiveIntegerField()),
                ('nid_number', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
