# Generated by Django 4.2.4 on 2023-09-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0002_alter_renter_id_alter_renter_number_of_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renter',
            name='password',
        ),
        migrations.AlterField(
            model_name='renter',
            name='phone_number1',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='renter',
            name='phone_number2',
            field=models.CharField(max_length=11),
        ),
    ]
