# Generated by Django 4.2.4 on 2023-09-05 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0002_alter_renter_id_alter_renter_number_of_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renter',
            name='password',
        ),
    ]
