# Generated by Django 4.2.4 on 2023-10-22 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flat_creation', '0002_rename_rent_id_id_flat_create_rent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat_create',
            name='rent_id',
        ),
    ]
