# Generated by Django 4.2.4 on 2023-10-25 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('flat_creation', '0003_remove_flat_create_rent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat_create',
            name='rent_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
    ]
