# Generated by Django 4.2.4 on 2023-10-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat_creation', '0004_flat_create_rent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat_create',
            name='flat_discout_price',
            field=models.IntegerField(default=True),
        ),
    ]
