# Generated by Django 4.2.4 on 2023-10-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat_creation', '0006_flat_create_flat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat_create',
            name='flat_name',
            field=models.TextField(max_length=1000),
        ),
    ]
