# Generated by Django 4.2.4 on 2023-10-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat_creation', '0009_alter_flat_create_flat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat_create',
            name='flat_discout_price',
            field=models.IntegerField(),
        ),
    ]
