# Generated by Django 4.2.4 on 2023-10-29 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flat_creation', '0011_rename_flat_discout_price_flat_create_flat_dis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat_create',
            old_name='flat_discount',
            new_name='discount_price',
        ),
    ]
