# Generated by Django 4.2.4 on 2023-10-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat_creation', '0012_rename_flat_discount_flat_create_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat_create',
            name='flat_dis',
            field=models.IntegerField(blank=True),
        ),
    ]
