# Generated by Django 4.2.4 on 2023-10-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat_creation', '0013_alter_flat_create_flat_dis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat_create',
            name='discount_price',
            field=models.IntegerField(blank=True),
        ),
    ]
