# Generated by Django 4.2.4 on 2023-10-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat_creation', '0014_alter_flat_create_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat_create',
            name='flat_dis',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
