# Generated by Django 4.2.4 on 2023-11-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat_creation', '0017_remove_flat_create_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat_create',
            name='dis_flat',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='flat_create',
            name='price_discount',
            field=models.IntegerField(blank=True),
        ),
    ]
